// src/app/features/auth/register/register.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, Validators, AbstractControl, ValidationErrors } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterLink],
  templateUrl: './register.component.html',
  styleUrl: './register.component.css'
})
export class RegisterComponent {
  private fb = inject(FormBuilder);
  private authService = inject(AuthService);
  private router = inject(Router);

  registerForm = this.fb.group({
    firstName: ['', Validators.required],
    lastName: ['', Validators.required],
    email: ['', [Validators.required, Validators.email]],
    phoneNumber: ['', [Validators.required, Validators.pattern('^[0-9+ ]{10,15}$')]],
    password: ['', [Validators.required, Validators.minLength(6)]],
    confirmPassword: ['', Validators.required],
    role: ['CUSTOMER', Validators.required]
  }, { validators: this.passwordMatchValidator });

  errorMessage: string | null = null;
  successMessage: string | null = null;
  loading = false;

  private passwordMatchValidator(control: AbstractControl): ValidationErrors | null {
    const password = control.get('password');
    const confirmPassword = control.get('confirmPassword');
    if (password && confirmPassword && password.value !== confirmPassword.value) {
      confirmPassword.setErrors({ passwordMismatch: true });
      return { passwordMismatch: true };
    }
    return null;
  }

  onSubmit(): void {
    if (this.registerForm.invalid) {
      this.registerForm.markAllAsTouched();
      return;
    }

    this.loading = true;
    this.errorMessage = null;
    this.successMessage = null;

    const payload = {
      email: this.registerForm.value.email,
      password: this.registerForm.value.password,
      role: this.registerForm.value.role,
      firstName: this.registerForm.value.firstName,
      lastName: this.registerForm.value.lastName,
      phoneNumber: this.registerForm.value.phoneNumber
    };

    this.authService.register(payload).subscribe({
      next: () => {
        this.loading = false;
        this.successMessage = 'Registration successful! Redirecting to login...';
        setTimeout(() => {
          this.router.navigate(['/auth/login']);
        }, 2000);
      },
      error: (err) => {
        this.loading = false;
        this.errorMessage = err.error?.message || 'Registration failed. Please try again.';
      }
    });
  }
}

<div class="auth-container">
  <div class="glass-card auth-card">
    <div class="auth-header">
      <span class="auth-logo-icon">⏳</span>
      <h2>Create Account</h2>
      <p class="auth-subtitle">Join HourSlot to easily book or list services</p>
    </div>

    @if (errorMessage) {
      <div class="error-alert">
        <span>⚠️</span> {{ errorMessage }}
      </div>
    }

    @if (successMessage) {
      <div class="success-alert">
        <span>✅</span> {{ successMessage }}
      </div>
    }

    <form [formGroup]="registerForm" (ngSubmit)="onSubmit()" class="auth-form">
      <div class="form-row">
        <div class="form-group half-width">
          <label for="firstName" class="form-label">First Name</label>
          <input 
            id="firstName" 
            type="text" 
            formControlName="firstName" 
            class="input-field" 
            placeholder="John"
            [class.input-error]="registerForm.get('firstName')?.touched && registerForm.get('firstName')?.invalid"
          />
          @if (registerForm.get('firstName')?.touched && registerForm.get('firstName')?.errors?.['required']) {
            <span class="validation-error">Required.</span>
          }
        </div>

        <div class="form-group half-width">
          <label for="lastName" class="form-label">Last Name</label>
          <input 
            id="lastName" 
            type="text" 
            formControlName="lastName" 
            class="input-field" 
            placeholder="Doe"
            [class.input-error]="registerForm.get('lastName')?.touched && registerForm.get('lastName')?.invalid"
          />
          @if (registerForm.get('lastName')?.touched && registerForm.get('lastName')?.errors?.['required']) {
            <span class="validation-error">Required.</span>
          }
        </div>
      </div>

      <div class="form-group">
        <label for="email" class="form-label">Email Address</label>
        <input 
          id="email" 
          type="email" 
          formControlName="email" 
          class="input-field" 
          placeholder="john.doe@example.com"
          [class.input-error]="registerForm.get('email')?.touched && registerForm.get('email')?.invalid"
        />
        @if (registerForm.get('email')?.touched && registerForm.get('email')?.errors?.['required']) {
          <span class="validation-error">Email is required.</span>
        }
        @if (registerForm.get('email')?.touched && registerForm.get('email')?.errors?.['email']) {
          <span class="validation-error">Please enter a valid email address.</span>
        }
      </div>

      <div class="form-group">
        <label for="phoneNumber" class="form-label">Phone Number</label>
        <input 
          id="phoneNumber" 
          type="text" 
          formControlName="phoneNumber" 
          class="input-field" 
          placeholder="+1 555 123 4567"
          [class.input-error]="registerForm.get('phoneNumber')?.touched && registerForm.get('phoneNumber')?.invalid"
        />
        @if (registerForm.get('phoneNumber')?.touched && registerForm.get('phoneNumber')?.errors?.['required']) {
          <span class="validation-error">Phone number is required.</span>
        }
        @if (registerForm.get('phoneNumber')?.touched && registerForm.get('phoneNumber')?.errors?.['pattern']) {
          <span class="validation-error">Invalid phone format (digits & spaces only, 10-15 chars).</span>
        }
      </div>

      <div class="form-group">
        <label class="form-label">I want to register as a:</label>
        <div class="role-selector">
          <label class="role-option" [class.selected]="registerForm.get('role')?.value === 'CUSTOMER'">
            <input type="radio" formControlName="role" value="CUSTOMER" class="hidden-radio" />
            <span class="role-icon">👤</span>
            <span class="role-text">Customer</span>
          </label>
          <label class="role-option" [class.selected]="registerForm.get('role')?.value === 'BUSINESS_ADMIN'">
            <input type="radio" formControlName="role" value="BUSINESS_ADMIN" class="hidden-radio" />
            <span class="role-icon">💼</span>
            <span class="role-text">Business</span>
          </label>
        </div>
      </div>

      <div class="form-group">
        <label for="password" class="form-label">Password</label>
        <input 
          id="password" 
          type="password" 
          formControlName="password" 
          class="input-field" 
          placeholder="Min 6 characters"
          [class.input-error]="registerForm.get('password')?.touched && registerForm.get('password')?.invalid"
        />
        @if (registerForm.get('password')?.touched && registerForm.get('password')?.errors?.['required']) {
          <span class="validation-error">Password is required.</span>
        }
        @if (registerForm.get('password')?.touched && registerForm.get('password')?.errors?.['minlength']) {
          <span class="validation-error">Password must be at least 6 characters.</span>
        }
      </div>

      <div class="form-group">
        <label for="confirmPassword" class="form-label">Confirm Password</label>
        <input 
          id="confirmPassword" 
          type="password" 
          formControlName="confirmPassword" 
          class="input-field" 
          placeholder="Confirm password"
          [class.input-error]="registerForm.get('confirmPassword')?.touched && registerForm.get('confirmPassword')?.invalid"
        />
        @if (registerForm.get('confirmPassword')?.touched && registerForm.get('confirmPassword')?.errors?.['required']) {
          <span class="validation-error">Please confirm your password.</span>
        }
        @if (registerForm.get('confirmPassword')?.touched && registerForm.hasError('passwordMismatch')) {
          <span class="validation-error">Passwords do not match.</span>
        }
      </div>

      <button type="submit" class="btn btn-primary btn-block" [disabled]="loading">
        @if (loading) {
          <span class="spinner"></span> Creating account...
        } @else {
          Create Account
        }
      </button>
    </form>

    <div class="auth-footer">
      <p>Already have an account? <a routerLink="/auth/login">Sign in</a></p>
    </div>
  </div>
</div>

// app/auth/register/page.tsx
'use client';

import { useState, FormEvent } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/lib/auth-context';
import styles from './register.module.css';

export default function RegisterPage() {
  const { register } = useAuth();
  const router = useRouter();

  const [formData, setFormData] = useState({
    firstName: '',
    lastName: '',
    email: '',
    phoneNumber: '',
    role: 'CUSTOMER',
    password: '',
    confirmPassword: '',
  });

  const [touched, setTouched] = useState<Record<string, boolean>>({});
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const errors: Record<string, string | null> = {};

  if (touched.firstName && !formData.firstName) {
    errors.firstName = 'Required.';
  }
  if (touched.lastName && !formData.lastName) {
    errors.lastName = 'Required.';
  }
  if (touched.email) {
    if (!formData.email) {
      errors.email = 'Email is required.';
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email)) {
      errors.email = 'Please enter a valid email address.';
    }
  }
  if (touched.phoneNumber) {
    if (!formData.phoneNumber) {
      errors.phoneNumber = 'Phone number is required.';
    } else if (!/^[0-9+ ]{10,15}$/.test(formData.phoneNumber)) {
      errors.phoneNumber = 'Invalid phone format (digits & spaces only, 10-15 chars).';
    }
  }
  if (touched.password) {
    if (!formData.password) {
      errors.password = 'Password is required.';
    } else if (formData.password.length < 6) {
      errors.password = 'Password must be at least 6 characters.';
    }
  }
  if (touched.confirmPassword) {
    if (!formData.confirmPassword) {
      errors.confirmPassword = 'Please confirm your password.';
    } else if (formData.password !== formData.confirmPassword) {
      errors.confirmPassword = 'Passwords do not match.';
    }
  }

  const handleInputChange = (field: string, value: string) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  const handleBlur = (field: string) => {
    setTouched((prev) => ({ ...prev, [field]: true }));
  };

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    
    // Mark all as touched
    const allTouched: Record<string, boolean> = {};
    Object.keys(formData).forEach((key) => {
      allTouched[key] = true;
    });
    setTouched(allTouched);

    // Re-check validation
    const hasErrors = 
      !formData.firstName ||
      !formData.lastName ||
      !formData.email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email) ||
      !formData.phoneNumber || !/^[0-9+ ]{10,15}$/.test(formData.phoneNumber) ||
      !formData.password || formData.password.length < 6 ||
      formData.password !== formData.confirmPassword;

    if (hasErrors) return;

    setLoading(true);
    setErrorMessage(null);
    setSuccessMessage(null);

    const payload = {
      email: formData.email,
      password: formData.password,
      role: formData.role,
      firstName: formData.firstName,
      lastName: formData.lastName,
      phoneNumber: formData.phoneNumber
    };

    try {
      await register(payload);
      setLoading(false);
      setSuccessMessage('Registration successful! Redirecting to login...');
      setTimeout(() => {
        router.push('/auth/login');
      }, 2000);
    } catch (err: any) {
      setLoading(false);
      setErrorMessage(err?.error?.message || 'Registration failed. Please try again.');
    }
  };

  return (
    <div className={styles.authContainer}>
      <div className={`glass-card ${styles.authCard}`}>
        <div className={styles.authHeader}>
          <span className={styles.authLogoIcon}>⏳</span>
          <h2>Create Account</h2>
          <p className={styles.authSubtitle}>Join HourSlot to easily book or list services</p>
        </div>

        {errorMessage && (
          <div className="error-alert">
            <span>⚠️</span> {errorMessage}
          </div>
        )}

        {successMessage && (
          <div className="success-alert">
            <span>✅</span> {successMessage}
          </div>
        )}

        <form onSubmit={handleSubmit} className={styles.authForm} noValidate>
          <div className="form-row">
            <div className="form-group half-width">
              <label htmlFor="firstName" className="form-label">First Name</label>
              <input
                id="firstName"
                type="text"
                className={`input-field${errors.firstName ? ' input-error' : ''}`}
                placeholder="John"
                value={formData.firstName}
                onChange={(e) => handleInputChange('firstName', e.target.value)}
                onBlur={() => handleBlur('firstName')}
              />
              {errors.firstName && <span className="validation-error">{errors.firstName}</span>}
            </div>

            <div className="form-group half-width">
              <label htmlFor="lastName" className="form-label">Last Name</label>
              <input
                id="lastName"
                type="text"
                className={`input-field${errors.lastName ? ' input-error' : ''}`}
                placeholder="Doe"
                value={formData.lastName}
                onChange={(e) => handleInputChange('lastName', e.target.value)}
                onBlur={() => handleBlur('lastName')}
              />
              {errors.lastName && <span className="validation-error">{errors.lastName}</span>}
            </div>
          </div>

          <div className="form-group">
            <label htmlFor="email" className="form-label">Email Address</label>
            <input
              id="email"
              type="email"
              className={`input-field${errors.email ? ' input-error' : ''}`}
              placeholder="john.doe@example.com"
              value={formData.email}
              onChange={(e) => handleInputChange('email', e.target.value)}
              onBlur={() => handleBlur('email')}
            />
            {errors.email && <span className="validation-error">{errors.email}</span>}
          </div>

          <div className="form-group">
            <label htmlFor="phoneNumber" className="form-label">Phone Number</label>
            <input
              id="phoneNumber"
              type="text"
              className={`input-field${errors.phoneNumber ? ' input-error' : ''}`}
              placeholder="+1 555 123 4567"
              value={formData.phoneNumber}
              onChange={(e) => handleInputChange('phoneNumber', e.target.value)}
              onBlur={() => handleBlur('phoneNumber')}
            />
            {errors.phoneNumber && <span className="validation-error">{errors.phoneNumber}</span>}
          </div>

          <div className="form-group">
            <label className="form-label">I want to register as a:</label>
            <div className={styles.roleSelector}>
              <label className={`${styles.roleOption} ${formData.role === 'CUSTOMER' ? styles.selected : ''}`}>
                <input
                  type="radio"
                  name="role"
                  value="CUSTOMER"
                  className={styles.hiddenRadio}
                  checked={formData.role === 'CUSTOMER'}
                  onChange={() => handleInputChange('role', 'CUSTOMER')}
                />
                <span className={styles.roleIcon}>👤</span>
                <span className={styles.roleText}>Customer</span>
              </label>
              <label className={`${styles.roleOption} ${formData.role === 'BUSINESS_ADMIN' ? styles.selected : ''}`}>
                <input
                  type="radio"
                  name="role"
                  value="BUSINESS_ADMIN"
                  className={styles.hiddenRadio}
                  checked={formData.role === 'BUSINESS_ADMIN'}
                  onChange={() => handleInputChange('role', 'BUSINESS_ADMIN')}
                />
                <span className={styles.roleIcon}>💼</span>
                <span className={styles.roleText}>Business</span>
              </label>
            </div>
          </div>

          <div className="form-group">
            <label htmlFor="password" className="form-label">Password</label>
            <input
              id="password"
              type="password"
              className={`input-field${errors.password ? ' input-error' : ''}`}
              placeholder="Min 6 characters"
              value={formData.password}
              onChange={(e) => handleInputChange('password', e.target.value)}
              onBlur={() => handleBlur('password')}
            />
            {errors.password && <span className="validation-error">{errors.password}</span>}
          </div>

          <div className="form-group">
            <label htmlFor="confirmPassword" className="form-label">Confirm Password</label>
            <input
              id="confirmPassword"
              type="password"
              className={`input-field${errors.confirmPassword ? ' input-error' : ''}`}
              placeholder="Confirm password"
              value={formData.confirmPassword}
              onChange={(e) => handleInputChange('confirmPassword', e.target.value)}
              onBlur={() => handleBlur('confirmPassword')}
            />
            {errors.confirmPassword && <span className="validation-error">{errors.confirmPassword}</span>}
          </div>

          <button type="submit" className="btn btn-primary btn-block" disabled={loading}>
            {loading ? <><span className="spinner" /> Creating account...</> : 'Create Account'}
          </button>
        </form>

        <div className={styles.authFooter}>
          <p>Already have an account? <Link href="/auth/login">Sign in</Link></p>
        </div>
      </div>
    </div>
  );
}
